run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - dupl
    - goconst
    - gocyclo
    - gofmt
    - revive
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - unused
    - unparam

linters-settings:
  dupl:
    threshold: 400
  lll:
    line-length: 170
  revive:
    confidence: 0.85