version: 1
reporting: checks-v1
policy:
  pullRequests: public
autoCancelPreviousChecks: true
tasks:
  $let:
    should_run:
      $if: 'tasks_for == "github-pull-request"'
      then: {$eval: 'event["action"] in ["opened", "reopened", "synchronize"]'}
      else: {$eval: 'tasks_for == "github-push"'}
    clone_url:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.clone_url}
      else: ${event.repository.clone_url}
    sha:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.sha}
      else: ${event.after}
  in:
  - $if: should_run
    then:
      provisionerId: proj-taskcluster
      workerType: ci
      deadline: {$fromNow: '1 day'}
      payload:
        maxRunTime: 3600
        image: "node:22"
        command:
          - "/bin/bash"
          - "-lc"
          - "git clone ${clone_url} repo && cd repo && git checkout ${sha} && yarn install && yarn test"
      metadata:
        name: "taskcluster-lib-urls node.js test"
        description: "Library for building taskcluster urls"
        owner: taskcluster-internal@mozilla.com
        source: ${clone_url}
  - $if: should_run
    then:
      provisionerId: proj-taskcluster
      workerType: ci
      deadline: {$fromNow: '1 day'}
      payload:
        maxRunTime: 3600
        image: 'golang:1.23'
        command:
          - /bin/bash
          - '-c'
          - |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0 &&
            git clone ${clone_url} repo
            cd repo
            git config advice.detachedHead false
            git checkout ${sha}
            go test -v -race ./...
            golangci-lint run
      metadata:
        name: "taskcluster-lib-urls go test"
        description: Run library test suite - golang 1.23
        owner: taskcluster-internal@mozilla.com
        source: ${clone_url}
  - $if: should_run
    then:
      provisionerId: proj-taskcluster
      workerType: ci
      deadline: {$fromNow: '1 day'}
      payload:
        maxRunTime: 3600
        image: 'maven:3.9-eclipse-temurin-21'
        command:
          - /bin/bash
          - '-c'
          - |
            git clone ${clone_url} repo
            cd repo
            git config advice.detachedHead false
            git checkout ${sha}
            mvn -X -e install
      metadata:
        name: taskcluster-lib-urls java test
        description: Run library test suite - java
        owner: taskcluster-internal@mozilla.com
        source: ${clone_url}
  - $if: should_run
    then:
      provisionerId: proj-taskcluster
      workerType: ci
      deadline: {$fromNow: '1 day'}
      payload:
        maxRunTime: 3600
        image: 'python:3.12'
        command:
          - /bin/bash
          - '-c'
          - |
            git clone ${clone_url} repo
            cd repo
            git config advice.detachedHead false
            git checkout ${sha}
            pip install tox
            tox -e py312
      metadata:
        name: taskcluster-lib-urls python 3.12 test
        description: Run library test suite - python3.12
        owner: taskcluster-internal@mozilla.com
        source: ${clone_url}
